import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { signIn, signOut, useSession } from 'next-auth/react'



const Home = () => {

  const { data: session } = useSession();
  
  console.log(session)
  return (
    <div>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {session ?(
          <>
          <h1>Welcome back {session.user.name}</h1>
          <button onClick= {() =>signOut()}>Log out</button>
          </>
        ):(
          <>
          <h1>You are not signed in</h1>
          <button onClick= {() =>signIn()}>Sign in</button>
          </>
        )}
      </main>
    </div>
  )
}

export default Home
